In [2]:
import numpy as np

## 2. Prove that $A^n = X\Lambda ^n X^{−1}$

Assuming A in invertible, we prove this by induction. 

For n=1 its given since 
$$A^1 = X\Lambda ^1 X^{−1} \rightarrow A = X\Lambda X^{−1}$$


Assuming the property holds for n (that is  $A^n = X\Lambda ^n X^{−1}$), we prove it for (n+1)
$$A^{n+1} = A^n\times A $$
by induction hypothesis
$$ = X\Lambda ^n X^{−1} \times X\Lambda X^{−1}  = X\Lambda ^{n+1} X^{−1} $$
**QED**

We can show this is the case for an example matrix.

In [104]:
# Matrices with determinant 1 have integer inverses
eigenvectors = np.array([
    [1, 2, 3, 2],
    [0, 1, 4, 3],
    [0, 0, 1, 2],
    [0, 0, 0, 1]
])
# Permute rows to make it look a bit more interesting
eigenvectors= eigenvectors[[2,0,3,1]]

eigenvalues = np.diag([5,4,3,9])

# Now we have an matrix A
A = eigenvectors@eigenvalues@np.linalg.inv(eigenvectors)
A

array([[ 3.,  0., 12.,  0.],
       [ 2.,  5., 10., -2.],
       [ 0.,  0.,  9.,  0.],
       [-4.,  0., 23.,  4.]])

In [76]:
A5 = np.linalg.matrix_power(A, 5)
# You can use the property that A^n = X*Lambda^n*X^-1
A5_eigenvectors = eigenvectors @ np.diag([5**5, 4**5, 3**5, 9**5]) @ np.linalg.inv(eigenvectors)

print("Are the two matrices the same?: ", (A5 == A5_eigenvectors).all())

Are the two matrices the same?:  True


## 4. Find determinants, eigenvector and eigen values
Let 
$$
S = \begin{bmatrix}
\cos \theta & -\sin \theta \\
\sin \theta & \cos \theta 
\end{bmatrix}
\begin{bmatrix}
2 & 0 \\
0 & 5 
\end{bmatrix}
\begin{bmatrix}
\cos \theta & \sin \theta \\
-\sin \theta & \cos \theta 
\end{bmatrix}
$$

Then we know that $T_1 = \begin{bmatrix} \cos \theta & -\sin \theta \\ \sin \theta & \cos \theta \end{bmatrix}$  is a rotation matrix that rotates a vector $\theta$ degrees counterclockwise.

Similarly we have that $T_2 = \begin{bmatrix} \cos \theta & \sin \theta \\ -\sin \theta & \cos \theta \end{bmatrix}$ is a rotation matrix that rotates a vector $\theta$ degrees clockwise.

So by multiplying by $S$ what we are truly doing is rotating clockwise $\theta$, then multiplying by $E = \begin{bmatrix} 2 & 0 \\ 0 & 5 \end{bmatrix}$ which is expanding on the X and Y axis by 2 and 5 respectevly and then is rotating everything counterclockwise $\theta$ degrees.

For the **determinant** it is easy to see that $T_1$ and $T_2$ are ortogonal and have determinant 0, similarly is easy to see that $det(E)=2*5=10$, so the determinant of $S$ can be calculated by 
$$det(S)= det(T_1 E T_2) = det(T_1)\times det(E) \times det(T_2) = 1 \times 10 \times 1 = 10$$

The **eigenvalues** are clearly 2 and 5, since we are expanding in $E$ by those values the first and second axis.

The **eigenvectors** are easy to find as well since what we need is to get the vectors that when $T_2$ is applied have either the first or the second axis null. We can rotate some vector like $\begin{bmatrix}1\\0 \end{bmatrix}$ that has the second axis nullyfied, by the inverse of $T_2$ which is $T_1$. 

Thus our eigenvector for the eigenvalue 2 is $T_1 \begin{bmatrix}1\\0 \end{bmatrix} = \begin{bmatrix}\cos \theta \\ \sin \theta \end{bmatrix}$

Similarly for eigenvalue 5 the eigenvector is $T_1 \begin{bmatrix}0\\1 \end{bmatrix} = \begin{bmatrix}-\sin \theta \\ \cos \theta \end{bmatrix}$

In [87]:
# Define theta
theta = np.radians(45)  # example value for theta in radians

# Define the rotation matrix 1
T1 = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])

# Define the diagonal matrix
E = np.array([
    [2, 0],
    [0, 5]
])

# Define the rotation matrix 2
T2 = np.array([
	[np.cos(theta), np.sin(theta)],
	[-np.sin(theta), np.cos(theta)]
])

S = T1 @ E @ T2
# Get the determinant of S
det_S = np.linalg.det(S)
print(f"Determinant of S: {det_S:.5f}")
# Get the eigenvalues and eigenvectors of S
eigenvalues, eigenvectors = np.linalg.eig(S)
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: \n", eigenvectors)

# Compare to calculated eigenvectors
eigenvectors_calculated = np.array([
    [np.cos(theta), -np.sin(theta)],
	[np.sin(theta), np.cos(theta)]
])
print("Calculated eigenvectors using properties: \n", eigenvectors_calculated)

Determinant of S: 10.00000
Eigenvalues:  [5. 2.]
Eigenvectors: 
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
Calculated eigenvectors using properties: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## Lazy random walk and random walk



In [50]:
def power_matrix(A, n):
	if n == 0:
		return np.eye(A.shape[0])
	if n == 1: 
		return A
	if n%2 == 0:
		return power_matrix(A@A, n//2)
	else:
		return A@power_matrix(A@A, n//2)