In [1]:
import numpy as np


# Linear Algebra

In [2]:
def vector_norm(x, p=2):
    return np.linalg.norm(x, p)

def dot_product(x, y):
    return np.dot(x, y)

def cross_product(x, y):
    return np.cross(x, y)

def transpose(x):
    return x.T

def multiply(x, y):
    return x @ y

def determinant(x):
    return np.linalg.det(x)

def inverse(x):
    return np.linalg.inv(x)

def compute_eigenvectors(x):
    vals, vecs = np.linalg.eig(x)
    return vals, vecs

def diagonalize(x):
    eigenvalues, eigenvectors = eigenvectors(x)
    D = np.diag(eigenvalues)
    eigenvectors_inv = inverse(eigenvectors)
    return eigenvectors, D, eigenvectors_inv

def is_orthogonal(x):
    return np.allclose(x @ x.T, np.eye(x.shape[0]))

def is_symmetric(x):
    return np.allclose(x, x.T)

def is_positive_semi_definite(x):
    return np.all(np.linalg.eigvals(x) >= 0)

def is_positive_definite(x):
    return np.all(np.linalg.eigvals(x) > 0)

def rank(x):
    return np.linalg.matrix_rank(x)

def sum_of_eigenvalues(x):
    return np.trace(x)

def product_of_eigenvalues(x):
    return determinant(x)

## Question 1

What could you say about these matrices: 
$$
\begin{pmatrix} -1 & \dfrac{3}{2} \\ 1 & -1 \end{pmatrix}
\begin{pmatrix} -1 & \dfrac{3}{2} \\ \dfrac{2}{3} & -1 \end{pmatrix}
\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix}
$$

### Code

In [3]:
A = np.array([[-1, 3/2], [1, -1]])
B = np.array([[-1, 3/2], [2/3, -1]])
C = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

determinant_A = determinant(A)
determinant_B = determinant(B)
determinant_C = determinant(C)

print(f'Determinant of A: {determinant_A}')
print(f'Determinant of B: {determinant_B}')
print(f'Determinant of C: {determinant_C}')
print()

eigenvalues_A, eigenvectors_A = compute_eigenvectors(A)
eigenvalues_B, eigenvectors_B = compute_eigenvectors(B)
eigenvalues_C, eigenvectors_C = compute_eigenvectors(C)

print(f'Eigenvalues of A: {eigenvalues_A}')
print(f'Eigenvectors of A:\n{eigenvectors_A}\n')

print(f'Eigenvalues of B: {eigenvalues_B}')
print(f'Eigenvectors of B:\n{eigenvectors_B}\n')

print(f'Eigenvalues of C: {eigenvalues_C}')
print(f'Eigenvectors of C:\n{eigenvectors_C}\n')

transpose_A = transpose(A)
transpose_B = transpose(B)
transpose_C = transpose(C)

print(f'Transpose of A:\n{transpose_A}\n')
print(f'Transpose of B:\n{transpose_B}\n')
print(f'Transpose of C:\n{transpose_C}\n')

Determinant of A: -0.5
Determinant of B: 0.0
Determinant of C: 1.0

Eigenvalues of A: [ 0.22474487 -2.22474487]
Eigenvectors of A:
[[ 0.77459667 -0.77459667]
 [ 0.63245553  0.63245553]]

Eigenvalues of B: [-1.11022302e-16 -2.00000000e+00]
Eigenvectors of B:
[[ 0.83205029 -0.83205029]
 [ 0.5547002   0.5547002 ]]

Eigenvalues of C: [1. 1. 1.]
Eigenvectors of C:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Transpose of A:
[[-1.   1. ]
 [ 1.5 -1. ]]

Transpose of B:
[[-1.          0.66666667]
 [ 1.5        -1.        ]]

Transpose of C:
[[1 0 0]
 [0 1 0]
 [0 0 1]]



### Formalization

**Properties of A**

- Non-zero determinant means that it is invertible and it is full-rank
- It has real and distinct eigenvalues, so it is diagonalizable
- It is not symmetric
- It is orthogonal

**Properties of B**

- Zero determinant means that it is not invertible and it is not full-rank
- Multiplying it with A will result in a non-invertible matrix as well
- It has real and distinct eigenvalues, so it is diagonalizable
- It is not symmetric
- Rank = 1 since there is just one non-zero eigenvalue

**Properties of C**

- It is an identity matrix of size 3x3
- It has a non-zero determinant, so it is invertible and full-rank
- It has real and distinct eigenvalues, so it is diagonalizable
- It is already diagonalized


| Property       | **Matrix A**                    | **Matrix B**                     | **Matrix C**             |
|----------------|---------------------------------|----------------------------------|--------------------------|
| **Size**       | 2 $\times$ 2                  | $2 \times 2$                   | $3 \times 3$           |
| **Determinant**| $-\dfrac{1}{2}$ (invertible)  | $0$ (singular)                 | $1$ (invertible)       |
| **Eigenvalues**| $-1 \pm \dfrac{\sqrt{6}}{2}$  | $0$ and $-2$                 | $1$, $1$, $1$      |
| **Symmetric**  | No                              | No                               | Yes                      |
| **Diagonalizable**| Yes (distinct eigenvalues)   | Yes (distinct eigenvalues)       | Yes (already diagonal)   |
| **Rank**       | $2$ (full rank)               | $1$                            | $3$ (full rank)        |
| **Orthogonal** | No                              | No                               | Yes                      |

## Question 2. 

Prove that $A^n = X\Lambda ^n X^{−1}$

### Formalization

Assuming A in invertible, we prove this by induction. 

For n=1 its given since 
$$A^1 = X\Lambda ^1 X^{−1} \rightarrow A = X\Lambda X^{−1}$$


Assuming the property holds for n (that is  $A^n = X\Lambda ^n X^{−1}$), we prove it for (n+1)
$$A^{n+1} = A^n\times A $$
by induction hypothesis
$$ = X\Lambda ^n X^{−1} \times X\Lambda X^{−1}  = X\Lambda ^{n+1} X^{−1} $$
**QED**

We can show this is the case for an example matrix.

### Code

In [4]:
# Matrices with determinant 1 have integer inverses
eigenvectors = np.array([
    [1, 2, 3, 2],
    [0, 1, 4, 3],
    [0, 0, 1, 2],
    [0, 0, 0, 1]
])
# Permute rows to make it look a bit more interesting
eigenvectors= eigenvectors[[2,0,3,1]]

eigenvalues = np.diag([5,4,3,9])

# Now we have an matrix A
A = eigenvectors@eigenvalues@np.linalg.inv(eigenvectors)
A

array([[ 3.,  0., 12.,  0.],
       [ 2.,  5., 10., -2.],
       [ 0.,  0.,  9.,  0.],
       [-4.,  0., 23.,  4.]])

In [5]:
A5 = np.linalg.matrix_power(A, 5)
# You can use the property that A^n = X*Lambda^n*X^-1
A5_eigenvectors = eigenvectors @ np.diag([5**5, 4**5, 3**5, 9**5]) @ np.linalg.inv(eigenvectors)

print("Are the two matrices the same?: ", (A5 == A5_eigenvectors).all())

Are the two matrices the same?:  True


## Question 3

Find the eigenvalues and unit eigenvectors of $A^TA$ and $AA^T$ with A = $\begin{pmatrix} 1 & 1 \\ 1 & 0 \end{pmatrix}$ Fibonacci matrix

### Code

In [6]:
A = np.array([[1, 1], [1, 0]])

ata = multiply(transpose(A), A)
aat = multiply(A, transpose(A))

print(f'A^T @ A:\n{ata}\n')
print(f'A @ A^T:\n{aat}\n')

eigenvalues_ata, eigenvectors_ata = compute_eigenvectors(ata)
eigenvalues_aat, eigenvectors_aat = compute_eigenvectors(aat)

print(f'Eigenvalues of A^T @ A: {eigenvalues_ata}')
print(f'Unit eigenvectors of A^T @ A:\n{eigenvectors_ata}\n')

print(f'Eigenvalues of A @ A^T: {eigenvalues_aat}')
print(f'Unit eigenvectors of A @ A^T:\n{eigenvectors_aat}\n')

A^T @ A:
[[2 1]
 [1 1]]

A @ A^T:
[[2 1]
 [1 1]]

Eigenvalues of A^T @ A: [2.61803399 0.38196601]
Unit eigenvectors of A^T @ A:
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]

Eigenvalues of A @ A^T: [2.61803399 0.38196601]
Unit eigenvectors of A @ A^T:
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]



### **Formalization**


In this case, $ A^T A $ and $ A A^T $ are **identical** because $ A $ is a **symmetric matrix** ($ A = A^T $).


- **Symmetry:**
  - Both $ A^T A $ and $ A A^T $ are **symmetric matrices**. This implies that they have real eigenvalues and their eigenvectors are orthogonal.

- **Positive Semi-Definiteness:**
  - Since $ A^T A $ and $ A A^T $ are formed by the product of a matrix with its transpose, they are **positive semi-definite**. Given that $ A $ is invertible (determinant $ \det(A) = -1 \neq 0 $), $ A^T A $ and $ A A^T $ are actually **positive definite**.

- **Eigenvalues:**
  - Both matrices share the **same eigenvalues** because they are similar matrices (i.e., $ A^T A $ and $ A A^T $ have the same non-zero eigenvalues).
  
- **Eigenvectors:**
  - The **unit eigenvectors** of $ A^T A $ and $ A A^T $ are identical in this case due to the symmetry and identical nature of the two matrices.
  - The eigenvectors are orthonormal, meaning they are both **unit vectors** and **mutually perpendicular**.

- **Diagonalization:**
  - Being symmetric and positive definite, both $ A^T A $ and $ A A^T $ are **diagonalizable**.

## Question 4. 
Find determinants, eigenvector and eigen values 
Without multiplying 

$$
S = \begin{bmatrix}
\cos \theta & -\sin \theta \\
\sin \theta & \cos \theta 
\end{bmatrix}
\begin{bmatrix}
2 & 0 \\
0 & 5 
\end{bmatrix}
\begin{bmatrix}
\cos \theta & \sin \theta \\
-\sin \theta & \cos \theta 
\end{bmatrix}
$$

find the determinant, the eigenvalues and eigenvectors, why S is positive definite

### Formalization

Let 
$$
S = \begin{bmatrix}
\cos \theta & -\sin \theta \\
\sin \theta & \cos \theta 
\end{bmatrix}
\begin{bmatrix}
2 & 0 \\
0 & 5 
\end{bmatrix}
\begin{bmatrix}
\cos \theta & \sin \theta \\
-\sin \theta & \cos \theta 
\end{bmatrix}
$$

Then we know that $T_1 = \begin{bmatrix} \cos \theta & -\sin \theta \\ \sin \theta & \cos \theta \end{bmatrix}$  is a rotation matrix that rotates a vector $\theta$ degrees counterclockwise.

Similarly we have that $T_2 = \begin{bmatrix} \cos \theta & \sin \theta \\ -\sin \theta & \cos \theta \end{bmatrix}$ is a rotation matrix that rotates a vector $\theta$ degrees clockwise.

So by multiplying by $S$ what we are truly doing is rotating clockwise $\theta$, then multiplying by $E = \begin{bmatrix} 2 & 0 \\ 0 & 5 \end{bmatrix}$ which is expanding on the X and Y axis by 2 and 5 respectevly and then is rotating everything counterclockwise $\theta$ degrees.

For the **determinant** it is easy to see that $T_1$ and $T_2$ are ortogonal and have determinant 1, similarly is easy to see that $det(E)=2*5=10$, so the determinant of $S$ can be calculated by 
$$det(S)= det(T_1 E T_2) = det(T_1)\times det(E) \times det(T_2) = 1 \times 10 \times 1 = 10$$

The **eigenvalues** are clearly 2 and 5, since we are expanding in $E$ by those values the first and second axis.

The **eigenvectors** are easy to find as well since what we need is to get the vectors that when $T_2$ is applied have either the first or the second axis null. We can rotate some vector like $\begin{bmatrix}1\\0 \end{bmatrix}$ that has the second axis nullyfied, by the inverse of $T_2$ which is $T_1$. 

Thus our eigenvector for the eigenvalue 2 is $T_1 \begin{bmatrix}1\\0 \end{bmatrix} = \begin{bmatrix}\cos \theta \\ \sin \theta \end{bmatrix}$

Similarly for eigenvalue 5 the eigenvector is $T_1 \begin{bmatrix}0\\1 \end{bmatrix} = \begin{bmatrix}-\sin \theta \\ \cos \theta \end{bmatrix}$

### Code

In [7]:
# Define theta
theta = np.radians(45)  # example value for theta in radians

# Define the rotation matrix 1
T1 = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])

# Define the diagonal matrix
E = np.array([
    [2, 0],
    [0, 5]
])

# Define the rotation matrix 2
T2 = np.array([
	[np.cos(theta), np.sin(theta)],
	[-np.sin(theta), np.cos(theta)]
])

S = T1 @ E @ T2
# Get the determinant of S
det_S = np.linalg.det(S)
print(f"Determinant of S: {det_S:.5f}")
# Get the eigenvalues and eigenvectors of S
eigenvalues, eigenvectors = np.linalg.eig(S)
print("Eigenvalues: ", eigenvalues)
print("Eigenvectors: \n", eigenvectors)

# Compare to calculated eigenvectors
eigenvectors_calculated = np.array([
    [np.cos(theta), -np.sin(theta)],
	[np.sin(theta), np.cos(theta)]
])
print("Calculated eigenvectors using properties: \n", eigenvectors_calculated)

Determinant of S: 10.00000
Eigenvalues:  [5. 2.]
Eigenvectors: 
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]
Calculated eigenvectors using properties: 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


## Question 5

For what numbers *c* and *d* such that **S** and **T** are positive definite 

$$
S = \begin{pmatrix} c & 1 & 1 \\ 1 & c & 1 \\ 1 & 1 & c \end{pmatrix}
T = \begin{pmatrix} 1 & 2 & 3 \\ 2 & d & 4 \\ 3 & 4 & 5 \end{pmatrix} 
$$

### Solution

A matrx is positive definite if all its eigenvalues are positive.

$
S = \begin{pmatrix}
c & 1 & 1 \\
1 & c & 1 \\
1 & 1 & c
\end{pmatrix}
$

Let $ S = cI + A $, where $ I $ is the identity matrix and $ A $ is:
$
A = \begin{pmatrix}
0 & 1 & 1 \\
1 & 0 & 1 \\
1 & 1 & 0
\end{pmatrix}
$

$
\det(A - \lambda I) = 0
$
$
\begin{vmatrix}
-\lambda & 1 & 1 \\
1 & -\lambda & 1 \\
1 & 1 & -\lambda
\end{vmatrix} = 0
$

$
-\lambda^3 + 3\lambda + 2 = 0
$

$
\lambda^3 - 3\lambda - 2 = 0
$

The eigenvalues of $ A $ are $ \lambda_1 = 2 $ and $ \lambda_2 = \lambda_3 = -1 $.

**Eigenvalues of $ S $:**
$
\mu_1 = c + 2 \\
\mu_2 = \mu_3 = c - 1
$

For $ S $ to be positive definite, all $ \mu_i > 0 $:

$
c + 2 > 0 \implies c > -2 \\
c - 1 > 0 \implies c > 1
$

The most restrictive condition is $ c > 1 $. Thus, $ S $ is positive definite when $ c > 1 $.



In [8]:
# Let c = 2

A = np.array([[2, 1, 1], [1, 2, 1], [1, 1, 2]])
eigenvalues_A, eigenvectors_A = compute_eigenvectors(A)

print(f"Eigenvalues of A: {eigenvalues_A}")
print("All are positive, so A is positive definite")

Eigenvalues of A: [1. 4. 1.]
All are positive, so A is positive definite




$
T = \begin{pmatrix}
1 & 2 & 3 \\
2 & d & 4 \\
3 & 4 & 5
\end{pmatrix}
$

$
\det(T - \lambda I) =
$
$
\begin{vmatrix}
1 - \lambda & 2 & 3 \\
2 & d - \lambda & 4 \\
3 & 4 & 5 - \lambda
\end{vmatrix} = 0
$

$
\lambda^3 - (d + 6)\lambda^2 - (24 - 6d)\lambda + (4d - 12) = 0
$

$
\text{Sum of eigenvalues} = \lambda_1 + \lambda_2 + \lambda_3 = d + 6 \\
\text{Product of eigenvalues} = \lambda_1 \lambda_2 \lambda_3 = (4d - 12)
$

For all eigenvalues to be positive:
1. $ d + 6 > 0 \implies d > -6 $.
2. $ 4d - 12 > 0 \implies d < 3 $.

Therefore, $ -6 < d < 3 $. 

But if $d \lt 3$, then the product of eigenvalues is $\le 0$, which means one of the eigenvalues if 0 or negative. Then, the matrix cannot be positive definite then.

**Conclusion:** There is no value of $d$ such that $T$ is positive definite.


## Question 6

Show that if $ \lambda_1, \lambda_2, \dots, \lambda_n $ are the eigenvalues of a matrix $ A $, then $ A^m $ has eigenvalues $ \lambda_1^m, \lambda_2^m, \dots, \lambda_n^m $.

**Proof using Induction**:

We prove this by induction on $ m $, the exponent of $ A $.

The base case is trivial since when $ m = 1 $, $ A^1 = A $ and the eigenvalues of $ A $ are $ \lambda_1, \lambda_2, \dots, \lambda_n $.


Le us assume that the statement holds for $ m = k $, i.e., $ A^k $ has eigenvalues $ \lambda_1^k, \lambda_2^k, \dots, \lambda_n^k $.
Then 

Consider $ A^{k+1} = A^k \cdot A $.
Let $ \mathbf{v} $ be an eigenvector of $ A $ corresponding to an eigenvalue $ \lambda $, i.e., $ A \mathbf{v} = \lambda \mathbf{v} $.
Then:
$$
A^{k+1} \mathbf{v} = A^k (A \mathbf{v}) = A^k (\lambda \mathbf{v}).
$$
Since $ \lambda $ is a scalar, then
$$
A^{k+1} \mathbf{v} = \lambda \cdot (A^k \mathbf{v}).
$$
By the inductive hypothesis, $ A^k \mathbf{v} = \lambda^k \mathbf{v} $, so:
$$
A^{k+1} \mathbf{v} = \lambda \cdot (\lambda^k \mathbf{v}) = \lambda^{k+1} \mathbf{v}.
$$
Thus $ \mathbf{v} $ is an eigenvector of $ A^{k+1} $ with eigenvalue $ \lambda^{k+1} $ as we wanted to show. A similar process follows for the rest of
the eigenvalues.




## Question 7

What is the determinant of any orthogonal matrix?

### Formalism

Let $ Q $ be an orthogonal matrix and $I$ is the identity matrix. Then:

$
Q^T Q = I
$

$
\det(Q^T Q) = \det(I)
$

$
\det(Q^T) \cdot \det(Q) = 1
$

$
[\det(Q)]^2 = 1
$

$
\det(Q) = \pm 1
$

**Any orthogonal matrix** Q satisfies:
$
\det(Q) = \pm 1
$


### Code

In [9]:
# Define an orthogonal matrix Q
Q = np.array([
    [0.6, -0.8],
    [0.8, 0.6]
])

# Verify that Q is orthogonal: Q.T @ Q should be the identity matrix
is_orthogonal = np.allclose(Q.T @ Q, np.eye(Q.shape[0]))
print(f"Is Q orthogonal? {is_orthogonal}")

# Compute the determinant of Q
det_Q = np.linalg.det(Q)
print(f"Determinant of Q: {det_Q}")

# Check if the determinant is either 1 or -1
is_det_valid = np.isclose(det_Q, 1) or np.isclose(det_Q, -1)
print(f"Is the determinant of Q either 1 or -1? {is_det_valid}")

Is Q orthogonal? True
Determinant of Q: 1.0
Is the determinant of Q either 1 or -1? True


## Question 8
For an undirected graph both the adjacency matrix and the Laplacian matrix are symmetric. Show that 
Laplacian is positive semi-definite matrix. Show that Laplacian that 0 is en eigenvalue (the smallest one).

### Formalism

Let us have the *incidence matrix* which has shape $m\times n$ 
$$
B(G) = 
\begin{cases} 
1 & \text{if there is an edge and a node } (v, w) \text{ and } v < w \\
-1 & \text{if there is an edge and a node } (v, w) \text{ and } v > w \\
0 & \text{otherwise.}
\end{cases}
$$


For example we have the graph $G$

![Graph](https://i.ibb.co/9NmP2Z5/Screenshot-from-2024-11-23-18-39-32.png)

$$
L_G = 
\begin{pmatrix}
3 & -1 & -1 & -1 \\
-1 & 1 & 0 & 0 \\
-1 & 0 & 1 & 0 \\
-1 & 0 & 0 & 1
\end{pmatrix}
$$

The incidence matrix  :

$$
B(G) = 
\begin{pmatrix}
1 & -1 & 0 & 0 \\
1 & 0 & -1 & 0 \\
1 & 0 & 0 & -1
\end{pmatrix}
$$


Then we want to prove that the laplacian matrix can be written as $L = B^T B$

**Proof**

Lets realize that for each cell $i,j$ , we have that they are the product of the $i$-th column of $B$ with the $j$-th column of B. Then we can differentiate three cases

1. $i=j$ : This is clearly the degree of $i$, since for each node that goes into it we add 1.
2. $i \not = j$ with no edge between $i$ and $j$: Then the "bitmap" of each column wont match in any node and the result will be 0 as expected
3. $i \not = j$ with an edge between $i$ and $j$: Then the "bitmap" matches in exactly one element where one is $-1$ and the other one is $1$. Thus the result is $-1$ as expected.

**QED**


Thus since we can express $L$ as $L = B^T B$ then it is positive semidefinite.


#### There is a 0 eigenvalue
Let us take $1$ as the vector of only $1$ in each component.

Then $L1 =(D-A)1 = D1 - A 1 = \text{degree vector} - \text{degree vector} = 0 $. Thus it has 0 as an eigenvalue.


